--QT 3-1
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME, ES.FIRST_NAME
FROM EMPLOYEES E, DEPARTMENTS D,EMPLOYEES ES  WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.MANAGER_ID = ES.EMPLOYEE_ID;
--QT 3-2
SELECT R.REGION_NAME, COUNTRY_NAME
FROM COUNTRIES C JOIN REGIONS R ON C.REGION_ID = R.REGION_ID ORDER BY REGION_NAME ASC, COUNTRY_NAME ASC;
--QT 3-3
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME, L.CITY, C.COUNTRY_NAME, REGION_NAME
FROM DEPARTMENTS D 
	JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID 
	JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID
	JOIN REGIONS R ON C.REGION_ID=R.REGION_ID
	LEFT JOIN EMPLOYEES E ON D.MANAGER_ID=E.EMPLOYEE_ID;
--QT 3-4
SELECT J.EMPLOYEE_ID, E.FIRST_NAME||' '||E.LAST_NAME FULL_NAME
FROM JOB_HISTORY J JOIN EMPLOYEES E ON J.JOB_ID='AC_ACCOUNT' AND J.EMPLOYEE_ID=E.EMPLOYEE_ID;
--QT 3-5
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID ORDER BY E.LAST_NAME;
--QT 3-6
SELECT E.EMPLOYEE_ID,E.FIRST_NAME 직원,E.HIRE_DATE,M.FIRST_NAME 매니저,M.HIRE_DATE
FROM EMPLOYEES E JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID WHERE E.HIRE_DATE<M.HIRE_DATE;
--QT 2-1
SELECT MIN(SALARY) 최저임금, MAX(SALARY) 최고임금, MAX(SALARY)-MIN(SALARY) AS "최고임금-최저임금"
FROM EMPLOYEES; 

--QT 2-2
SELECT TO_CHAR(MAX(HIRE_DATE),'yyyy "년" mm"월" dd"일"')
FROM EMPLOYEES;

--QT 2-3
SELECT JOB_ID 업무,AVG(SALARY)평균연봉,MAX(SALARY)최고연봉,MIN(SALARY)최저연봉
FROM EMPLOYEES GROUP BY JOB_ID ORDER BY 2 DESC,3 DESC,4 DESC;

--QT 2-4
SELECT TO_CHAR(MIN(HIRE_DATE),'yyyy "년" mm"월" dd"일"')
FROM EMPLOYEES;

--QT 2-5
SELECT DEPARTMENT_ID 부서, AVG(SALARY) 평균임금, MIN(SALARY) 최저임금, AVG(SALARY)-MIN(SALARY) AS "평균-최저임금차이"
FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY)-MIN(SALARY)<2000 ORDER BY 4 DESC;

SELECT JOB_ID, MAX(SALARY)최고임금,MIN(SALARY)최저임금,MAX(SALARY)-MIN(SALARY) AS "최고-최저임금차이"
FROM EMPLOYEES
GROUP BY JOB_ID ORDER BY 4 DESC;