
SELECT FIRST_NAME||LAST_NAME �씠由�,SALARY �씠硫붿씪, PHONE_NUMBER �쟾�솕踰덊샇 FROM EMPLOYEE ORDER BY HIRE_DATE;

SELECT JOB_TITLE,MAX_SALARY FROM JOBS ORDER BY MAX_SALARY DESC;
SELECT COUNT(ID) FROM EMPLOYEE WHERE MANAGER_ID IS NULL;
SELECT JOB_TITLE FROM JOBS ORDER BY JOB_TITLE DESC, MAX_SALARY DESC;
SELECT COUNT(DEPARTMENT_ID) FROM DEPARTMENTS;
SELECT DEPARTMENT_NAME FROM DEPARTMENTS ORDER BY LENGTH(DEPARTMENT_NAME) DESC;
SELECT COUNT(DEPARTMENT_NAME)FROM DEPARTMENTS WHERE MANAGER_ID IS NULL; 
SELECT INITCAP(COUNTRY_NAME)FROM COUNTRIES ORDER BY COUNTRY_NAME;  
SELECT REGION_NAME FROM REGIONS ORDER BY LENGTH(REGION_NAME);
SELECT DISTINCT LOWER(CITY) FROM LOCATIONS  ORDER BY LOWER(CITY) ASC;
